spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop